//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurlStudio.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurlStudio.UI.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {about} ähnelt.
        /// </summary>
        public static string Common_DateTime_About {
            get {
                return ResourceManager.GetString("Common.DateTime.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {a minute} ähnelt.
        /// </summary>
        public static string Common_DateTime_AboutAMinute {
            get {
                return ResourceManager.GetString("Common.DateTime.AboutAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {about a month} ähnelt.
        /// </summary>
        public static string Common_DateTime_AboutAMonth {
            get {
                return ResourceManager.GetString("Common.DateTime.AboutAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {about an hour} ähnelt.
        /// </summary>
        public static string Common_DateTime_AboutAnHour {
            get {
                return ResourceManager.GetString("Common.DateTime.AboutAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {about a year} ähnelt.
        /// </summary>
        public static string Common_DateTime_AboutAYear {
            get {
                return ResourceManager.GetString("Common.DateTime.AboutAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {a day} ähnelt.
        /// </summary>
        public static string Common_DateTime_ADay {
            get {
                return ResourceManager.GetString("Common.DateTime.ADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {days} ähnelt.
        /// </summary>
        public static string Common_DateTime_Days {
            get {
                return ResourceManager.GetString("Common.DateTime.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {hours} ähnelt.
        /// </summary>
        public static string Common_DateTime_Hours {
            get {
                return ResourceManager.GetString("Common.DateTime.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {less than a minute} ähnelt.
        /// </summary>
        public static string Common_DateTime_LessThanAMinute {
            get {
                return ResourceManager.GetString("Common.DateTime.LessThanAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {minutes} ähnelt.
        /// </summary>
        public static string Common_DateTime_Minutes {
            get {
                return ResourceManager.GetString("Common.DateTime.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {months} ähnelt.
        /// </summary>
        public static string Common_DateTime_Months {
            get {
                return ResourceManager.GetString("Common.DateTime.Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {} ähnelt.
        /// </summary>
        public static string Common_DateTime_Prefix_Ago {
            get {
                return ResourceManager.GetString("Common.DateTime.Prefix.Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {} ähnelt.
        /// </summary>
        public static string Common_DateTime_Prefix_FromNow {
            get {
                return ResourceManager.GetString("Common.DateTime.Prefix.FromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ago} ähnelt.
        /// </summary>
        public static string Common_DateTime_Suffix_Ago {
            get {
                return ResourceManager.GetString("Common.DateTime.Suffix.Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {from now} ähnelt.
        /// </summary>
        public static string Common_DateTime_Suffix_FromNow {
            get {
                return ResourceManager.GetString("Common.DateTime.Suffix.FromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {years} ähnelt.
        /// </summary>
        public static string Common_DateTime_Years {
            get {
                return ResourceManager.GetString("Common.DateTime.Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Common.Exception.Title} ähnelt.
        /// </summary>
        public static string Common_Exception_Title {
            get {
                return ResourceManager.GetString("Common.Exception.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Common.Undefined} ähnelt.
        /// </summary>
        public static string Common_Undefined {
            get {
                return ResourceManager.GetString("Common.Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.Close} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_Close {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseAll} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseAll {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseLeft} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseLeft {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseOthers} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseOthers {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseRight} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseRight {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Add} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Add {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Collection.EmptyList} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Collection_EmptyList {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Collection.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Collection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Collection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Collection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Environment.EmptyList} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Environment_EmptyList {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Environment.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Environment.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Environment_Title {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Environment.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.File.EmptyList} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_File_EmptyList {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.File.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.File.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_File_Title {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.File.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Folder.EmptyList} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Folder_EmptyList {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Folder.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Folder.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Folder_Title {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Folder.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Section.CollapseAll.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Section_CollapseAll_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Section.CollapseAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.File.Settings.Section.ExpandAll.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Document_File_Settings_Section_ExpandAll_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Document.File.Settings.Section.ExpandAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.ImportCollection.Description} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_ImportCollection_Description {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.ImportCollection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.ImportCollection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_ImportCollection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.ImportCollection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.NewCollection.Description} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_NewCollection_Description {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.NewCollection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.NewCollection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_NewCollection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.NewCollection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.OpenCollection.Description} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_OpenCollection_Description {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.OpenCollection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.OpenCollection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_OpenCollection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.OpenCollection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Headline} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Headline {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.RecentFiles} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_RecentFiles {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFile} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFile {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFile.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFile.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFolder} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFolder {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFolder.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFolder_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFolder.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.Properties} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_Properties {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.Rename} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_Rename {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.RevealInExplorer} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_RevealInExplorer {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.RevealInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.File.Properties} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_File_Properties {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.File.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.File.Rename} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_File_Rename {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.File.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.File.RevealInExplorer} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_File_RevealInExplorer {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.File.RevealInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFile} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFile {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFile.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFile.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFolder} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFolder {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFolder.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFolder_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFolder.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.Properties} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_Properties {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.Rename} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_Rename {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.RevealInExplorer} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_RevealInExplorer {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.RevealInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Title} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Title {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.CollapseAll.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_CollapseAll_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.CollapseAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.ExpandAll.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_ExpandAll_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.ExpandAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.More.AddCollection} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_More_AddCollection {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.More.AddCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.More.OpenCollection} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_More_OpenCollection {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.More.OpenCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.More.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_More_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.More.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.FileSettings.Title} ähnelt.
        /// </summary>
        public static string Dock_Tool_FileSettings_Title {
            get {
                return ResourceManager.GetString("Dock.Tool.FileSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.Button.Cancel} ähnelt.
        /// </summary>
        public static string MessageBox_Button_Cancel {
            get {
                return ResourceManager.GetString("MessageBox.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.Button.Discard} ähnelt.
        /// </summary>
        public static string MessageBox_Button_Discard {
            get {
                return ResourceManager.GetString("MessageBox.Button.Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.Button.OK} ähnelt.
        /// </summary>
        public static string MessageBox_Button_OK {
            get {
                return ResourceManager.GetString("MessageBox.Button.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.Button.Save} ähnelt.
        /// </summary>
        public static string MessageBox_Button_Save {
            get {
                return ResourceManager.GetString("MessageBox.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.ErrorTitle} ähnelt.
        /// </summary>
        public static string MessageBox_ErrorTitle {
            get {
                return ResourceManager.GetString("MessageBox.ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AllowInsecureSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_AllowInsecureSetting_Label {
            get {
                return ResourceManager.GetString("Setting.AllowInsecureSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AllowInsecureSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_AllowInsecureSetting_Title {
            get {
                return ResourceManager.GetString("Setting.AllowInsecureSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AllowInsecureSetting.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_AllowInsecureSetting_Tooltip {
            get {
                return ResourceManager.GetString("Setting.AllowInsecureSetting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AwsSigV4Setting.Provider1.Label} ähnelt.
        /// </summary>
        public static string Setting_AwsSigV4Setting_Provider1_Label {
            get {
                return ResourceManager.GetString("Setting.AwsSigV4Setting.Provider1.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AwsSigV4Setting.Provider2.Label} ähnelt.
        /// </summary>
        public static string Setting_AwsSigV4Setting_Provider2_Label {
            get {
                return ResourceManager.GetString("Setting.AwsSigV4Setting.Provider2.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AwsSigV4Setting.Region.Label} ähnelt.
        /// </summary>
        public static string Setting_AwsSigV4Setting_Region_Label {
            get {
                return ResourceManager.GetString("Setting.AwsSigV4Setting.Region.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AwsSigV4Setting.Service.Label} ähnelt.
        /// </summary>
        public static string Setting_AwsSigV4Setting_Service_Label {
            get {
                return ResourceManager.GetString("Setting.AwsSigV4Setting.Service.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.AwsSigV4Setting.Title} ähnelt.
        /// </summary>
        public static string Setting_AwsSigV4Setting_Title {
            get {
                return ResourceManager.GetString("Setting.AwsSigV4Setting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.BasicUserSetting.NoEncryptionHint} ähnelt.
        /// </summary>
        public static string Setting_BasicUserSetting_NoEncryptionHint {
            get {
                return ResourceManager.GetString("Setting.BasicUserSetting.NoEncryptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.BasicUserSetting.Password.Label} ähnelt.
        /// </summary>
        public static string Setting_BasicUserSetting_Password_Label {
            get {
                return ResourceManager.GetString("Setting.BasicUserSetting.Password.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.BasicUserSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_BasicUserSetting_Title {
            get {
                return ResourceManager.GetString("Setting.BasicUserSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.BasicUserSetting.User.Label} ähnelt.
        /// </summary>
        public static string Setting_BasicUserSetting_User_Label {
            get {
                return ResourceManager.GetString("Setting.BasicUserSetting.User.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CaCertSetting.File.Label} ähnelt.
        /// </summary>
        public static string Setting_CaCertSetting_File_Label {
            get {
                return ResourceManager.GetString("Setting.CaCertSetting.File.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CaCertSetting.File.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_CaCertSetting_File_Tooltip {
            get {
                return ResourceManager.GetString("Setting.CaCertSetting.File.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CaCertSetting.FilePicker.Pattern.Title} ähnelt.
        /// </summary>
        public static string Setting_CaCertSetting_FilePicker_Pattern_Title {
            get {
                return ResourceManager.GetString("Setting.CaCertSetting.FilePicker.Pattern.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CaCertSetting.FilePicker.Title} ähnelt.
        /// </summary>
        public static string Setting_CaCertSetting_FilePicker_Title {
            get {
                return ResourceManager.GetString("Setting.CaCertSetting.FilePicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CaCertSetting.FilePicker.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_CaCertSetting_FilePicker_Tooltip {
            get {
                return ResourceManager.GetString("Setting.CaCertSetting.FilePicker.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CaCertSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_CaCertSetting_Title {
            get {
                return ResourceManager.GetString("Setting.CaCertSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ClientCertificateSetting.CertificateFile.Label} ähnelt.
        /// </summary>
        public static string Setting_ClientCertificateSetting_CertificateFile_Label {
            get {
                return ResourceManager.GetString("Setting.ClientCertificateSetting.CertificateFile.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ClientCertificateSetting.FilePicker.Title} ähnelt.
        /// </summary>
        public static string Setting_ClientCertificateSetting_FilePicker_Title {
            get {
                return ResourceManager.GetString("Setting.ClientCertificateSetting.FilePicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ClientCertificateSetting.FilePicker.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_ClientCertificateSetting_FilePicker_Tooltip {
            get {
                return ResourceManager.GetString("Setting.ClientCertificateSetting.FilePicker.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ClientCertificateSetting.KeyFile.Label} ähnelt.
        /// </summary>
        public static string Setting_ClientCertificateSetting_KeyFile_Label {
            get {
                return ResourceManager.GetString("Setting.ClientCertificateSetting.KeyFile.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ClientCertificateSetting.Password.Label} ähnelt.
        /// </summary>
        public static string Setting_ClientCertificateSetting_Password_Label {
            get {
                return ResourceManager.GetString("Setting.ClientCertificateSetting.Password.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ClientCertificateSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_ClientCertificateSetting_Title {
            get {
                return ResourceManager.GetString("Setting.ClientCertificateSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ConnectToSetting.HostAndPort1.Label} ähnelt.
        /// </summary>
        public static string Setting_ConnectToSetting_HostAndPort1_Label {
            get {
                return ResourceManager.GetString("Setting.ConnectToSetting.HostAndPort1.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ConnectToSetting.HostAndPort2.Label} ähnelt.
        /// </summary>
        public static string Setting_ConnectToSetting_HostAndPort2_Label {
            get {
                return ResourceManager.GetString("Setting.ConnectToSetting.HostAndPort2.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ConnectToSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_ConnectToSetting_Title {
            get {
                return ResourceManager.GetString("Setting.ConnectToSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ContinueOnErrorSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_ContinueOnErrorSetting_Label {
            get {
                return ResourceManager.GetString("Setting.ContinueOnErrorSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ContinueOnErrorSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_ContinueOnErrorSetting_Title {
            get {
                return ResourceManager.GetString("Setting.ContinueOnErrorSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ContinueOnErrorSetting.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_ContinueOnErrorSetting_Tooltip {
            get {
                return ResourceManager.GetString("Setting.ContinueOnErrorSetting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.OpenReadFile.FilePicker.Title} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_OpenReadFile_FilePicker_Title {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.OpenReadFile.FilePicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.OpenReadFile.FilePicker.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_OpenReadFile_FilePicker_Tooltip {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.OpenReadFile.FilePicker.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.OpenReadFile.Label} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_OpenReadFile_Label {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.OpenReadFile.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.OpenWriteFile.FilePicker.Title} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_OpenWriteFile_FilePicker_Title {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.OpenWriteFile.FilePicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.OpenWriteFile.FilePicker.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_OpenWriteFile_FilePicker_Tooltip {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.OpenWriteFile.FilePicker.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.OpenWriteFile.Label} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_OpenWriteFile_Label {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.OpenWriteFile.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.CookieSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_CookieSetting_Title {
            get {
                return ResourceManager.GetString("Setting.CookieSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.DelaySetting.Label} ähnelt.
        /// </summary>
        public static string Setting_DelaySetting_Label {
            get {
                return ResourceManager.GetString("Setting.DelaySetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.DelaySetting.Title} ähnelt.
        /// </summary>
        public static string Setting_DelaySetting_Title {
            get {
                return ResourceManager.GetString("Setting.DelaySetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.Disabled.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_Disabled_Tooltip {
            get {
                return ResourceManager.GetString("Setting.Disabled.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.Enabled.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_Enabled_Tooltip {
            get {
                return ResourceManager.GetString("Setting.Enabled.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.FileRootSetting.FolderPicker.Title} ähnelt.
        /// </summary>
        public static string Setting_FileRootSetting_FolderPicker_Title {
            get {
                return ResourceManager.GetString("Setting.FileRootSetting.FolderPicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.FileRootSetting.FolderPicker.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_FileRootSetting_FolderPicker_Tooltip {
            get {
                return ResourceManager.GetString("Setting.FileRootSetting.FolderPicker.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.FileRootSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_FileRootSetting_Label {
            get {
                return ResourceManager.GetString("Setting.FileRootSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.FileRootSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_FileRootSetting_Title {
            get {
                return ResourceManager.GetString("Setting.FileRootSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.HttpVersionSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_HttpVersionSetting_Label {
            get {
                return ResourceManager.GetString("Setting.HttpVersionSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.HttpVersionSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_HttpVersionSetting_Title {
            get {
                return ResourceManager.GetString("Setting.HttpVersionSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {HTTP/1.0} ähnelt.
        /// </summary>
        public static string Setting_HttpVersionSetting_Version_Http10 {
            get {
                return ResourceManager.GetString("Setting.HttpVersionSetting.Version.Http10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {HTTP/1.1} ähnelt.
        /// </summary>
        public static string Setting_HttpVersionSetting_Version_Http11 {
            get {
                return ResourceManager.GetString("Setting.HttpVersionSetting.Version.Http11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {HTTP/2} ähnelt.
        /// </summary>
        public static string Setting_HttpVersionSetting_Version_Http20 {
            get {
                return ResourceManager.GetString("Setting.HttpVersionSetting.Version.Http20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {HTTP/3} ähnelt.
        /// </summary>
        public static string Setting_HttpVersionSetting_Version_Http30 {
            get {
                return ResourceManager.GetString("Setting.HttpVersionSetting.Version.Http30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.IgnoreAssertsSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_IgnoreAssertsSetting_Label {
            get {
                return ResourceManager.GetString("Setting.IgnoreAssertsSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.IgnoreAssertsSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_IgnoreAssertsSetting_Title {
            get {
                return ResourceManager.GetString("Setting.IgnoreAssertsSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.IgnoreAssertsSetting.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_IgnoreAssertsSetting_Tooltip {
            get {
                return ResourceManager.GetString("Setting.IgnoreAssertsSetting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.IpVersionSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_IpVersionSetting_Label {
            get {
                return ResourceManager.GetString("Setting.IpVersionSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.IpVersionSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_IpVersionSetting_Title {
            get {
                return ResourceManager.GetString("Setting.IpVersionSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Auto} ähnelt.
        /// </summary>
        public static string Setting_IpVersionSetting_Version_Auto {
            get {
                return ResourceManager.GetString("Setting.IpVersionSetting.Version.Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {IPv4} ähnelt.
        /// </summary>
        public static string Setting_IpVersionSetting_Version_IPv4 {
            get {
                return ResourceManager.GetString("Setting.IpVersionSetting.Version.IPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {IPv6} ähnelt.
        /// </summary>
        public static string Setting_IpVersionSetting_Version_IPv6 {
            get {
                return ResourceManager.GetString("Setting.IpVersionSetting.Version.IPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.MaxFilesizeSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_MaxFilesizeSetting_Label {
            get {
                return ResourceManager.GetString("Setting.MaxFilesizeSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.MaxFilesizeSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_MaxFilesizeSetting_Title {
            get {
                return ResourceManager.GetString("Setting.MaxFilesizeSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.File.FilePicker.Title} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_File_FilePicker_Title {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.File.FilePicker.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.File.FilePicker.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_File_FilePicker_Tooltip {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.File.FilePicker.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.File.Label} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_File_Label {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.File.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.File.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_File_Tooltip {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.File.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.IsAutomatic.Label} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_IsAutomatic_Label {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.IsAutomatic.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.IsAutomatic.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_IsAutomatic_Tooltip {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.IsAutomatic.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.IsOptional.Label} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_IsOptional_Label {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.IsOptional.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.IsOptional.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_IsOptional_Tooltip {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.IsOptional.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NetrcSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_NetrcSetting_Title {
            get {
                return ResourceManager.GetString("Setting.NetrcSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NoProxySetting.Add.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_NoProxySetting_Add_Tooltip {
            get {
                return ResourceManager.GetString("Setting.NoProxySetting.Add.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NoProxySetting.EmptyList} ähnelt.
        /// </summary>
        public static string Setting_NoProxySetting_EmptyList {
            get {
                return ResourceManager.GetString("Setting.NoProxySetting.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NoProxySetting.Remove.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_NoProxySetting_Remove_Tooltip {
            get {
                return ResourceManager.GetString("Setting.NoProxySetting.Remove.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.NoProxySetting.Title} ähnelt.
        /// </summary>
        public static string Setting_NoProxySetting_Title {
            get {
                return ResourceManager.GetString("Setting.NoProxySetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.Overwritten.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_Overwritten_Tooltip {
            get {
                return ResourceManager.GetString("Setting.Overwritten.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.PathAsIsSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_PathAsIsSetting_Label {
            get {
                return ResourceManager.GetString("Setting.PathAsIsSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.PathAsIsSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_PathAsIsSetting_Title {
            get {
                return ResourceManager.GetString("Setting.PathAsIsSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.PathAsIsSetting.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_PathAsIsSetting_Tooltip {
            get {
                return ResourceManager.GetString("Setting.PathAsIsSetting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ProxySetting.Description} ähnelt.
        /// </summary>
        public static string Setting_ProxySetting_Description {
            get {
                return ResourceManager.GetString("Setting.ProxySetting.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ProxySetting.HostAndPort.Label} ähnelt.
        /// </summary>
        public static string Setting_ProxySetting_HostAndPort_Label {
            get {
                return ResourceManager.GetString("Setting.ProxySetting.HostAndPort.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ProxySetting.Password.Label} ähnelt.
        /// </summary>
        public static string Setting_ProxySetting_Password_Label {
            get {
                return ResourceManager.GetString("Setting.ProxySetting.Password.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ProxySetting.Protocol.Label} ähnelt.
        /// </summary>
        public static string Setting_ProxySetting_Protocol_Label {
            get {
                return ResourceManager.GetString("Setting.ProxySetting.Protocol.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ProxySetting.Title} ähnelt.
        /// </summary>
        public static string Setting_ProxySetting_Title {
            get {
                return ResourceManager.GetString("Setting.ProxySetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ProxySetting.User.Label} ähnelt.
        /// </summary>
        public static string Setting_ProxySetting_User_Label {
            get {
                return ResourceManager.GetString("Setting.ProxySetting.User.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.AllowRedirections.Label} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_AllowRedirections_Label {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.AllowRedirections.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.AllowRedirections.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_AllowRedirections_Tooltip {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.AllowRedirections.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.MaxRedirections.Label} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_MaxRedirections_Label {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.MaxRedirections.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.MaxRedirections.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_MaxRedirections_Tooltip {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.MaxRedirections.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.RedirectionsTrusted.Label} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_RedirectionsTrusted_Label {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.RedirectionsTrusted.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.RedirectionsTrusted.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_RedirectionsTrusted_Tooltip {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.RedirectionsTrusted.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RedirectionsSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_RedirectionsSetting_Title {
            get {
                return ResourceManager.GetString("Setting.RedirectionsSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ResolveSetting.Address.Label} ähnelt.
        /// </summary>
        public static string Setting_ResolveSetting_Address_Label {
            get {
                return ResourceManager.GetString("Setting.ResolveSetting.Address.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ResolveSetting.Address.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_ResolveSetting_Address_Tooltip {
            get {
                return ResourceManager.GetString("Setting.ResolveSetting.Address.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ResolveSetting.HostAndPort.Label} ähnelt.
        /// </summary>
        public static string Setting_ResolveSetting_HostAndPort_Label {
            get {
                return ResourceManager.GetString("Setting.ResolveSetting.HostAndPort.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ResolveSetting.HostAndPort.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_ResolveSetting_HostAndPort_Tooltip {
            get {
                return ResourceManager.GetString("Setting.ResolveSetting.HostAndPort.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ResolveSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_ResolveSetting_Title {
            get {
                return ResourceManager.GetString("Setting.ResolveSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RetrySetting.RetryCount.Label} ähnelt.
        /// </summary>
        public static string Setting_RetrySetting_RetryCount_Label {
            get {
                return ResourceManager.GetString("Setting.RetrySetting.RetryCount.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RetrySetting.RetryCount.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_RetrySetting_RetryCount_Tooltip {
            get {
                return ResourceManager.GetString("Setting.RetrySetting.RetryCount.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RetrySetting.RetryInterval.Label} ähnelt.
        /// </summary>
        public static string Setting_RetrySetting_RetryInterval_Label {
            get {
                return ResourceManager.GetString("Setting.RetrySetting.RetryInterval.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RetrySetting.RetryInterval.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_RetrySetting_RetryInterval_Tooltip {
            get {
                return ResourceManager.GetString("Setting.RetrySetting.RetryInterval.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.RetrySetting.Title} ähnelt.
        /// </summary>
        public static string Setting_RetrySetting_Title {
            get {
                return ResourceManager.GetString("Setting.RetrySetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.SslNoRevokeSetting.Label} ähnelt.
        /// </summary>
        public static string Setting_SslNoRevokeSetting_Label {
            get {
                return ResourceManager.GetString("Setting.SslNoRevokeSetting.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.SslNoRevokeSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_SslNoRevokeSetting_Title {
            get {
                return ResourceManager.GetString("Setting.SslNoRevokeSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.SslNoRevokeSetting.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_SslNoRevokeSetting_Tooltip {
            get {
                return ResourceManager.GetString("Setting.SslNoRevokeSetting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.TimeoutSetting.ConnectTimeoutSeconds.Label} ähnelt.
        /// </summary>
        public static string Setting_TimeoutSetting_ConnectTimeoutSeconds_Label {
            get {
                return ResourceManager.GetString("Setting.TimeoutSetting.ConnectTimeoutSeconds.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.TimeoutSetting.ConnectTimeoutSeconds.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_TimeoutSetting_ConnectTimeoutSeconds_Tooltip {
            get {
                return ResourceManager.GetString("Setting.TimeoutSetting.ConnectTimeoutSeconds.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.TimeoutSetting.MaxTimeSeconds.Label} ähnelt.
        /// </summary>
        public static string Setting_TimeoutSetting_MaxTimeSeconds_Label {
            get {
                return ResourceManager.GetString("Setting.TimeoutSetting.MaxTimeSeconds.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.TimeoutSetting.MaxTimeSeconds.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_TimeoutSetting_MaxTimeSeconds_Tooltip {
            get {
                return ResourceManager.GetString("Setting.TimeoutSetting.MaxTimeSeconds.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.TimeoutSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_TimeoutSetting_Title {
            get {
                return ResourceManager.GetString("Setting.TimeoutSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ToEntrySetting.Title} ähnelt.
        /// </summary>
        public static string Setting_ToEntrySetting_Title {
            get {
                return ResourceManager.GetString("Setting.ToEntrySetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ToEntrySetting.ToEntry.Label} ähnelt.
        /// </summary>
        public static string Setting_ToEntrySetting_ToEntry_Label {
            get {
                return ResourceManager.GetString("Setting.ToEntrySetting.ToEntry.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.ToEntrySetting.ToEntry.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_ToEntrySetting_ToEntry_Tooltip {
            get {
                return ResourceManager.GetString("Setting.ToEntrySetting.ToEntry.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.UnixSocketSetting.Path.Label} ähnelt.
        /// </summary>
        public static string Setting_UnixSocketSetting_Path_Label {
            get {
                return ResourceManager.GetString("Setting.UnixSocketSetting.Path.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.UnixSocketSetting.Path.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_UnixSocketSetting_Path_Tooltip {
            get {
                return ResourceManager.GetString("Setting.UnixSocketSetting.Path.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.UnixSocketSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_UnixSocketSetting_Title {
            get {
                return ResourceManager.GetString("Setting.UnixSocketSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.UserAgentSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_UserAgentSetting_Title {
            get {
                return ResourceManager.GetString("Setting.UserAgentSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.UserAgentSetting.UserAgent.Tooltip} ähnelt.
        /// </summary>
        public static string Setting_UserAgentSetting_UserAgent_Tooltip {
            get {
                return ResourceManager.GetString("Setting.UserAgentSetting.UserAgent.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.VariableSetting.Description} ähnelt.
        /// </summary>
        public static string Setting_VariableSetting_Description {
            get {
                return ResourceManager.GetString("Setting.VariableSetting.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Setting.VariableSetting.Title} ähnelt.
        /// </summary>
        public static string Setting_VariableSetting_Title {
            get {
                return ResourceManager.GetString("Setting.VariableSetting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Label} ähnelt.
        /// </summary>
        public static string View_Editor_Label {
            get {
                return ResourceManager.GetString("View.Editor.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.MessageBox.UnsavedChanges.Text} ähnelt.
        /// </summary>
        public static string View_Editor_MessageBox_UnsavedChanges_Text {
            get {
                return ResourceManager.GetString("View.Editor.MessageBox.UnsavedChanges.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.MessageBox.UnsavedChanges.Title} ähnelt.
        /// </summary>
        public static string View_Editor_MessageBox_UnsavedChanges_Title {
            get {
                return ResourceManager.GetString("View.Editor.MessageBox.UnsavedChanges.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Back.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Back_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Back.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Forward.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Forward_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Forward.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Open.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Open_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Open.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Redo.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Redo_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Redo.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Save.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Save_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Save.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.SaveAll.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_SaveAll_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.SaveAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.ShowEndOfLine.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_ShowEndOfLine_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.ShowEndOfLine.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.ShowWhitespace.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_ShowWhitespace_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.ShowWhitespace.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Undo.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Undo_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Undo.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.WordWrap.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_WordWrap_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.WordWrap.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.ActivityText.LoadingCollections} ähnelt.
        /// </summary>
        public static string View_Loading_ActivityText_LoadingCollections {
            get {
                return ResourceManager.GetString("View.Loading.ActivityText.LoadingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.ActivityText.LoadingEnvironments} ähnelt.
        /// </summary>
        public static string View_Loading_ActivityText_LoadingEnvironments {
            get {
                return ResourceManager.GetString("View.Loading.ActivityText.LoadingEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.Label} ähnelt.
        /// </summary>
        public static string View_Loading_Label {
            get {
                return ResourceManager.GetString("View.Loading.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.Title} ähnelt.
        /// </summary>
        public static string View_Loading_Title {
            get {
                return ResourceManager.GetString("View.Loading.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File {
            get {
                return ResourceManager.GetString("View.Main.Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.Exit} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_Exit {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.New} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_New {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.New.Collection} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_New_Collection {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.New.Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.New.File} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_New_File {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.New.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.OpenCollection} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_OpenCollection {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.OpenCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.Save} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_Save {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.SaveAll} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.StatusBar.NotificationsList.EmptyList} ähnelt.
        /// </summary>
        public static string View_Main_StatusBar_NotificationsList_EmptyList {
            get {
                return ResourceManager.GetString("View.Main.StatusBar.NotificationsList.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.StatusBar.NotificationsList.Title} ähnelt.
        /// </summary>
        public static string View_Main_StatusBar_NotificationsList_Title {
            get {
                return ResourceManager.GetString("View.Main.StatusBar.NotificationsList.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.StatusBar.NotificationsList.Tooltip} ähnelt.
        /// </summary>
        public static string View_Main_StatusBar_NotificationsList_Tooltip {
            get {
                return ResourceManager.GetString("View.Main.StatusBar.NotificationsList.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.StatusBar.Status.Idle.Text} ähnelt.
        /// </summary>
        public static string View_Main_StatusBar_Status_Idle_Text {
            get {
                return ResourceManager.GetString("View.Main.StatusBar.Status.Idle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.StatusBar.Status.OpeningFile.Text} ähnelt.
        /// </summary>
        public static string View_Main_StatusBar_Status_OpeningFile_Text {
            get {
                return ResourceManager.GetString("View.Main.StatusBar.Status.OpeningFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Window.Main.Title} ähnelt.
        /// </summary>
        public static string Window_Main_Title {
            get {
                return ResourceManager.GetString("Window.Main.Title", resourceCulture);
            }
        }
    }
}
