//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurlStudio.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurlStudio.UI.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.Close} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_Close {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseAll} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseAll {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseLeft} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseLeft {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseOthers} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseOthers {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.ContextMenu.CloseRight} ähnelt.
        /// </summary>
        public static string Dock_Document_ContextMenu_CloseRight {
            get {
                return ResourceManager.GetString("Dock.Document.ContextMenu.CloseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.ImportCollection.Description} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_ImportCollection_Description {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.ImportCollection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.ImportCollection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_ImportCollection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.ImportCollection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.NewCollection.Description} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_NewCollection_Description {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.NewCollection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.NewCollection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_NewCollection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.NewCollection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.OpenCollection.Description} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_OpenCollection_Description {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.OpenCollection.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Actions.OpenCollection.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Actions_OpenCollection_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Actions.OpenCollection.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Headline} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Headline {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.RecentFiles} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_RecentFiles {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Document.Welcome.Title} ähnelt.
        /// </summary>
        public static string Dock_Document_Welcome_Title {
            get {
                return ResourceManager.GetString("Dock.Document.Welcome.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFile} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFile {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFile.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFile.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFolder} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFolder {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.AddFolder.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_AddFolder_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.AddFolder.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.Properties} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_Properties {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Collection.Rename} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Collection_Rename {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Collection.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.File.Properties} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_File_Properties {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.File.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.File.Rename} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_File_Rename {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.File.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFile} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFile {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFile.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFile.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFolder} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFolder {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.AddFolder.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_AddFolder_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.AddFolder.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.Properties} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_Properties {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Folder.Rename} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Folder_Rename {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Folder.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Title} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Title {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.CollapseAll.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_CollapseAll_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.CollapseAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.ExpandAll.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_ExpandAll_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.ExpandAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.More.AddCollection} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_More_AddCollection {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.More.AddCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.More.OpenCollection} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_More_OpenCollection {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.More.OpenCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.Tool.CollectionExplorer.Toolbar.More.Tooltip} ähnelt.
        /// </summary>
        public static string Dock_Tool_CollectionExplorer_Toolbar_More_Tooltip {
            get {
                return ResourceManager.GetString("Dock.Tool.CollectionExplorer.Toolbar.More.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Dock.FileSettings.Title} ähnelt.
        /// </summary>
        public static string Dock_Tool_FileSettings_Title {
            get {
                return ResourceManager.GetString("Dock.Tool.FileSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.ErrorTitle} ähnelt.
        /// </summary>
        public static string MessageBox_ErrorTitle {
            get {
                return ResourceManager.GetString("MessageBox.ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Back.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Back_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Back.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Forward.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Forward_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Forward.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Open.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Open_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Open.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Save.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Save_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Save.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.SaveAll.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_SaveAll_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.SaveAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.ActivityText.LoadingCollections} ähnelt.
        /// </summary>
        public static string View_Loading_ActivityText_LoadingCollections {
            get {
                return ResourceManager.GetString("View.Loading.ActivityText.LoadingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.ActivityText.LoadingEnvironments} ähnelt.
        /// </summary>
        public static string View_Loading_ActivityText_LoadingEnvironments {
            get {
                return ResourceManager.GetString("View.Loading.ActivityText.LoadingEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.Title} ähnelt.
        /// </summary>
        public static string View_Loading_Title {
            get {
                return ResourceManager.GetString("View.Loading.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File {
            get {
                return ResourceManager.GetString("View.Main.Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.Exit} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_Exit {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.New} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_New {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.New.Collection} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_New_Collection {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.New.Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.New.File} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_New_File {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.New.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.OpenCollection} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_OpenCollection {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.OpenCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.Save} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_Save {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.SaveAll} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Window.Main.Title} ähnelt.
        /// </summary>
        public static string Window_Main_Title {
            get {
                return ResourceManager.GetString("Window.Main.Title", resourceCulture);
            }
        }
    }
}
