//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurlStudio.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HurlStudio.UI.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {MessageBox.ErrorTitle} ähnelt.
        /// </summary>
        public static string MessageBox_ErrorTitle {
            get {
                return ResourceManager.GetString("MessageBox.ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.CollectionExplorer.Title} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_CollectionExplorer_Title {
            get {
                return ResourceManager.GetString("View.Editor.Dock.CollectionExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.CollectionExplorer.Toolbar.OpenCollection.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_CollectionExplorer_Toolbar_OpenCollection_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Dock.CollectionExplorer.Toolbar.OpenCollection.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.Document.ContextMenu.Close} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_Document_ContextMenu_Close {
            get {
                return ResourceManager.GetString("View.Editor.Dock.Document.ContextMenu.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.Document.ContextMenu.CloseAll} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_Document_ContextMenu_CloseAll {
            get {
                return ResourceManager.GetString("View.Editor.Dock.Document.ContextMenu.CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.Document.ContextMenu.CloseLeft} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_Document_ContextMenu_CloseLeft {
            get {
                return ResourceManager.GetString("View.Editor.Dock.Document.ContextMenu.CloseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.Document.ContextMenu.CloseOthers} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_Document_ContextMenu_CloseOthers {
            get {
                return ResourceManager.GetString("View.Editor.Dock.Document.ContextMenu.CloseOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.Document.ContextMenu.CloseRight} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_Document_ContextMenu_CloseRight {
            get {
                return ResourceManager.GetString("View.Editor.Dock.Document.ContextMenu.CloseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Dock.FileSettings.Title} ähnelt.
        /// </summary>
        public static string View_Editor_Dock_FileSettings_Title {
            get {
                return ResourceManager.GetString("View.Editor.Dock.FileSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Back.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Back_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Back.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Forward.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Forward_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Forward.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Load.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Load_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Load.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.Save.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_Save_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.Save.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Editor.Toolbar.SaveAll.Tooltip} ähnelt.
        /// </summary>
        public static string View_Editor_Toolbar_SaveAll_Tooltip {
            get {
                return ResourceManager.GetString("View.Editor.Toolbar.SaveAll.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.ActivityText.LoadingCollections} ähnelt.
        /// </summary>
        public static string View_Loading_ActivityText_LoadingCollections {
            get {
                return ResourceManager.GetString("View.Loading.ActivityText.LoadingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.ActivityText.LoadingEnvironments} ähnelt.
        /// </summary>
        public static string View_Loading_ActivityText_LoadingEnvironments {
            get {
                return ResourceManager.GetString("View.Loading.ActivityText.LoadingEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Loading.Title} ähnelt.
        /// </summary>
        public static string View_Loading_Title {
            get {
                return ResourceManager.GetString("View.Loading.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File {
            get {
                return ResourceManager.GetString("View.Main.Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.Exit} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_Exit {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.Save} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_Save {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {View.Main.Menu.File.SaveAll} ähnelt.
        /// </summary>
        public static string View_Main_Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("View.Main.Menu.File.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Window.Main.Title} ähnelt.
        /// </summary>
        public static string Window_Main_Title {
            get {
                return ResourceManager.GetString("Window.Main.Title", resourceCulture);
            }
        }
    }
}
